### ISSUE TITLE
About deprecation

### ISSUE THREAD

**Issue by SukkaW** [hexojs/hexo-notify#42]
@tomap @curbengh @YoshinoriN @hexojs/core 

The notify plugin here hasn't been maintained for a long time.

With `hexo-log@2` releases (https://github.com/hexojs/hexo-log/releases/tag/2.0.0), the `hexo-bunyan` along with the Stream support are now dropped, which means the notify plugin is no longer compatible with newest `hexo-log`. So it is time to deprecate `hexo-notify`.

We could implement a notify plugin directly inside `hexo-log` if someone really needs the plugin.

**Comment by yoshinorin** [comment]
Done :)
I will archive this repo.
